accelerator: gpu
aic21_track3_extract: false
auto_lr_find: true
aux_loss: true
backbone: resnet50
batch_size: 4
bbox_loss_coef: 0
benchmark: false
check_val_every_n_epoch: 1
checkpoints_path: null
cls_loss_coef: 7
cost_feats_weight:
- 0.16666666666666666
- 0.16666666666666666
- 0.16666666666666666
- 0.16666666666666666
- 0.3333333333333333
cpu_testing: false
data_dir: ../data/coco
dataset_file: coco_data
dec_layers: 6
dec_n_points: 4
deterministic: false
devices:
- 0
- 1
- 2
- 3
- 4
- 5
- 6
- 7
- 8
- 10
- 11
- 12
- 13
- 14
- 15
devices_: '[0,1,2,3,4,5,6,7,8,10,11,12,13,14,15]'
dice_loss_coef: 1
dilation: false
dim_feedforward: 1024
dropout: 0.1
enc_layers: 6
enc_n_points: 4
fast_dev_run: false
fast_dev_run_all: false
focal_alpha: 0.25
giou_loss_coef: 0
gradient_clip_val: 0.1
hidden_dim: 256
load_best: false
load_dir: null
load_v_num: null
load_ver: null
log_dir: lightning_logs
'log_every_n_steps ': 50
lr: 0.0002
lr_backbone: 2.0e-05
lr_backbone_names:
- backbone.0
lr_decay_min_lr: 1.0e-05
lr_decay_rate: 0.1
lr_decay_steps: 40
lr_linear_proj_mult: 0.1
lr_linear_proj_names:
- reference_points
- sampling_offsets
lr_scheduler: step
mask_loss_coef: 1
masks: false
max_epochs: 70
model_name: deformable_detr
model_summary_deep: 2
n_coor_bins: 1000
n_wh_bins: 1000
nheads: 8
num_feat: 5
num_feature_levels: 4
num_group_norm: 32
num_queries: 300
num_sanity_val_steps: 0
num_workers: 16
number_using_data: -1
optimizer: adamw
position_embedding: sine
position_embedding_scale: 6.283185307179586
precision: 32
profiler: simple
remove_difficult: false
save_checkpoint: true
seed: 1709
seq_output: true
set_cost_bbox: 5
set_cost_class: 7
set_cost_giou: 2
shared_voca: true
strategy: ddp
swa: 0.0
tune_model: false
two_stage: false
weight_decay: 0.0001
with_box_refine: false
